//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.GpsSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GpsSvc.ICustomerServices")]
    public interface ICustomerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/GetFavorites", ReplyAction="http://tempuri.org/ICustomerServices/GetFavoritesResponse")]
        string GetFavorites(out string favoriteMovie, out string favoriteLanguage, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/UpdateFavoritesByName", ReplyAction="http://tempuri.org/ICustomerServices/UpdateFavoritesByNameResponse")]
        string UpdateFavoritesByName(string firstName, string lastName, string favoriteMovie, string favoriteLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/GetCustomerList", ReplyAction="http://tempuri.org/ICustomerServices/GetCustomerListResponse")]
        string GetCustomerList(out System.Data.DataSet customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/AddACustomer", ReplyAction="http://tempuri.org/ICustomerServices/AddACustomerResponse")]
        string AddACustomer(string firstName, string lastName, string favoriteMovie, string favoriteLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/AddGpsData", ReplyAction="http://tempuri.org/ICustomerServices/AddGpsDataResponse")]
        string AddGpsData(string userId, string deviceId, string time, string longitude, string latitude, string altitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/GetGpsData", ReplyAction="http://tempuri.org/ICustomerServices/GetGpsDataResponse")]
        string GetGpsData(out System.Data.DataSet gpsData, string userId, string deviceId, string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/DeleteGpsData", ReplyAction="http://tempuri.org/ICustomerServices/DeleteGpsDataResponse")]
        string DeleteGpsData(string userId, string deviceId, string startTime, string endTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServicesChannel : TestService.GpsSvc.ICustomerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServicesClient : System.ServiceModel.ClientBase<TestService.GpsSvc.ICustomerServices>, TestService.GpsSvc.ICustomerServices {
        
        public CustomerServicesClient() {
        }
        
        public CustomerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFavorites(out string favoriteMovie, out string favoriteLanguage, string firstName, string lastName) {
            return base.Channel.GetFavorites(out favoriteMovie, out favoriteLanguage, firstName, lastName);
        }
        
        public string UpdateFavoritesByName(string firstName, string lastName, string favoriteMovie, string favoriteLanguage) {
            return base.Channel.UpdateFavoritesByName(firstName, lastName, favoriteMovie, favoriteLanguage);
        }
        
        public string GetCustomerList(out System.Data.DataSet customers) {
            return base.Channel.GetCustomerList(out customers);
        }
        
        public string AddACustomer(string firstName, string lastName, string favoriteMovie, string favoriteLanguage) {
            return base.Channel.AddACustomer(firstName, lastName, favoriteMovie, favoriteLanguage);
        }
        
        public string AddGpsData(string userId, string deviceId, string time, string longitude, string latitude, string altitude) {
            return base.Channel.AddGpsData(userId, deviceId, time, longitude, latitude, altitude);
        }
        
        public string GetGpsData(out System.Data.DataSet gpsData, string userId, string deviceId, string startTime, string endTime) {
            return base.Channel.GetGpsData(out gpsData, userId, deviceId, startTime, endTime);
        }
        
        public string DeleteGpsData(string userId, string deviceId, string startTime, string endTime) {
            return base.Channel.DeleteGpsData(userId, deviceId, startTime, endTime);
        }
    }
}
